mcts :
  playouts : 1
  c_PUCT : 0.85
  temperature :
    exploration : 1
    exploitation: 0.01

network :
  blocks : 5
  filters : 8
  eval : 
    dense : 8
  policy :
    dirichlet :
      epsilon : 0.25
      alpha : 0.03
  loss :
    L2_norm : 0.01
  training :
    optimizer : adam

selfplay :
  minibatches : 10
  learning_rate : 0.001
  selfplay_games : 1
  selfplay_tests : 1
  random_tests : 1